name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

isar_version: &isar_version 3.1.8 # define the version to be used

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.2.2
  intl: ^0.19.0
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.4
  window_manager: ^0.3.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - .env
